== Prerequisites

The following prerequisites must be met to start using {redfish-provider-full}:

* Physical system with an embedded BMC that supports {redfish}.
* Administrator credentials for the BMC.
* {product-appliance} must be able to reach physical system's BMC.

For {redfish} events to work, the BMC must support the Server-Side Events
(SSE) technology.

=== Physical system provisioning additionally requires:

* DHCP server that is configured for PXE boot.
* PXE server, consisting of:
** A set of Operating System boot and installation files.
** A PXELinux menu or iPXE script containing menu entries for all available
   Operating Systems.
** TFTP service that is capable of serving a Network Bootstrap Program (NBP),
   boot menus and Operating System images.
** HTTP(S) service for serving customization templates (kickstart, sysprep
   files) and Operating System images.
** NFS or SMB service with read and write access to the files that are
   served over TFTP and HTTP(S) during the network boot process and Operating
   System installation.
* The target physical system must be able to perform a network boot on at
  least one of its system's NICs (not the BMC network).

Typically, PXE server has network boot files stored under _/var/lib/tftpboot_
and this is what needs to be shared over NFS or SMB. Boot menus are usually
placed in the _pxelinux.cfg_ subfolder and are available for download over
TFTP. Customization templates are most often stored in the _customization_
subfolder and can be downloaded over HTTP(S).

=== Firmware Update feature additionally requires:

* A Firmware Registry service that provides the information on the available
  firmware update binaries.
* A file serving service to provide the actual firmware update binaries.

The Firmware Registry service has to provide tagged firmware update binaries
(the `manufacturer` and the `model` tags) where both of the tag values must
match target system's exact values. The firmware registry can be a simple
RESTful service that supports basic HTTP authentication and  responds to a HTTP
`GET` request with a JSON-formated response such as the following one:

    [
      {
        "id": 1,
        "description": "DELL BIOS update",
        "version": "10.4.3",
        "filename": "dell-bios-2019-03-23.bin",
        "urls": [
          "http://172.16.93.126:8080/files/dell-bios-2019-03-23.bin",
          "https://172.16.93.126:8443/files/dell-bios-2019-03-23.bin"
        ],
        "compatible_server_models": [
          {
            "manufacturer": "Dell",
            "model": "PowerEdge R740"
          }
        ]
      },
      ...
    ]


== Tested Systems

We have tested the {redfish-provider} against the following systems:

* Dell PowerEdge R630 with iDRAC8 version 2.60.60.60
* Dell PowerEdge R640 with iDRAC9 version 3.30.30.30
* Dell PowerEdge R740xd with iDRAC9 version 3.30.30.30
* HPE ProLiant DL360 Gen10 with iLO 5 version 1.40 and licensed with iLO
  Standard license
* Supermicro System SuperServer series X11SDV version 1.25 with OOB and
  SFT-DCMS-Single license

== Installing {product-title}
To install {product-title} please refer to
link:https://access.redhat.com/documentation/en/red-hat-cloudforms/[{product-title} Installation Guide].
