== Prerequisites

The following preprequisites must be met to start using {redfish-provider-full}:

* One or more physical systems with an embedded BMC that supports {redfish}.
* Administrator credentials for the BMC.
* {product-appliance} must be able to reach {redfish-server} on the physical
  system's BMC network interface through at least one of the appliance's own
  network interface.
* For {redfish} events to work, the BMC must support the Server-Side Events
  (SSE) technology.
* One or more functional PXE servers must be configured and running on a network
  that is accessible both to {product-appliance}. They need to offer SAMBA or
  NFS write access, and read-only TFTP and HTTPS access. They also need to be
  populated with the appropriate Operating System boot and installation files.
* The target systems must be able to perform a network boot on at least one of
  their system's NICs (not the BMC network). This NIC must be able to reach the
  PXE server.

== Tested Systems

We have tested the {redfish-provider} against the following systems:

* Dell PowerEdge R630 with iDRAC8 version 2.60.60.60
* Dell PowerEdge R640 with iDRAC9 version 3.30.30.30
* Dell PowerEdge R740xd with iDRAC9 version 3.30.30.30
* HPE ProLiant DL360 Gen10 with iLO 5 version 1.40 and licensed with iLO
  Standard license
* Supermicro System SuperServer series X11SDV version 1.25 with OOB and
  SFT-DCMS-Single license

== Installing {product-title}
To install {product-title} please refer to
link:https://access.redhat.com/documentation/en/red-hat-cloudforms/[{product-title} Installation Guide].