== Prerequisites

The following prerequisites must be met to start using {redfish-provider-full}:

* Physical system with an embedded BMC that supports {redfish}.
* Administrator credentials for the BMC.
* {product-appliance} must be able to reach physical system's BMC.

For {redfish} events to work, the BMC must support the Server-Side Events
(SSE) technology.

Physical system provisioning additionally requires:

* DHCP server that is configured for PXE boot.
* PXE server, consisting of:
** A set of Operating System boot and installation files.
** A PXELinux menu or iPXE script containing menu entries for all available
   Operating Systems.
** TFTP service that is capable of serving a Network Bootstrap Program (NBP),
   boot menus and Operating System images.
** HTTP(S) service for serving customization templates (kickstart, sysprep
   files) and Operating System images.
** NFS or SMB service with read and write access to the files that are
   served over TFTP and HTTP(S) during the network boot process and Operating
   System installation.
* The target physical system must be able to perform a network boot on at
  least one of its system's NICs (not the BMC network).

Typically, PXE server has network boot files stored under _/var/lib/tftpboot_
and this is what needs to be shared over NFS or SMB. Boot menus are usually
placed in the _pxelinux.cfg_ subfolder and are available for download over
TFTP. Customization templates are most often stored in the _customization_
subfolder and can be downloaded over HTTP(S).

== Tested Systems

We have tested the {redfish-provider} against the following systems:

* Dell PowerEdge R630 with iDRAC8 version 2.60.60.60
* Dell PowerEdge R640 with iDRAC9 version 3.30.30.30
* Dell PowerEdge R740xd with iDRAC9 version 3.30.30.30
* HPE ProLiant DL360 Gen10 with iLO 5 version 1.40 and licensed with iLO
  Standard license
* Supermicro System SuperServer series X11SDV version 1.25 with OOB and
  SFT-DCMS-Single license

== Installing {product-title}
To install {product-title} please refer to
link:https://access.redhat.com/documentation/en/red-hat-cloudforms/[{product-title} Installation Guide].
